// source: proto/candlestick.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.candlestick.Candlestick', null, global);
goog.exportSymbol('proto.candlestick.Candlesticks', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.candlestick.Candlestick = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.candlestick.Candlestick, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.candlestick.Candlestick.displayName = 'proto.candlestick.Candlestick';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.candlestick.Candlesticks = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.candlestick.Candlesticks.repeatedFields_, null);
};
goog.inherits(proto.candlestick.Candlesticks, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.candlestick.Candlesticks.displayName = 'proto.candlestick.Candlesticks';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.candlestick.Candlestick.prototype.toObject = function(opt_includeInstance) {
  return proto.candlestick.Candlestick.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.candlestick.Candlestick} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.candlestick.Candlestick.toObject = function(includeInstance, msg) {
  var f, obj = {
    volume: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    open: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    close: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    high: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    low: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    timestamp: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.candlestick.Candlestick}
 */
proto.candlestick.Candlestick.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.candlestick.Candlestick;
  return proto.candlestick.Candlestick.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.candlestick.Candlestick} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.candlestick.Candlestick}
 */
proto.candlestick.Candlestick.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setVolume(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setOpen(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setClose(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setHigh(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLow(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.candlestick.Candlestick.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.candlestick.Candlestick.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.candlestick.Candlestick} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.candlestick.Candlestick.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVolume();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getOpen();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getClose();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getHigh();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getLow();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
};


/**
 * optional double volume = 1;
 * @return {number}
 */
proto.candlestick.Candlestick.prototype.getVolume = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.candlestick.Candlestick} returns this
 */
proto.candlestick.Candlestick.prototype.setVolume = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double open = 2;
 * @return {number}
 */
proto.candlestick.Candlestick.prototype.getOpen = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.candlestick.Candlestick} returns this
 */
proto.candlestick.Candlestick.prototype.setOpen = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double close = 3;
 * @return {number}
 */
proto.candlestick.Candlestick.prototype.getClose = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.candlestick.Candlestick} returns this
 */
proto.candlestick.Candlestick.prototype.setClose = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double high = 4;
 * @return {number}
 */
proto.candlestick.Candlestick.prototype.getHigh = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.candlestick.Candlestick} returns this
 */
proto.candlestick.Candlestick.prototype.setHigh = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double low = 5;
 * @return {number}
 */
proto.candlestick.Candlestick.prototype.getLow = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.candlestick.Candlestick} returns this
 */
proto.candlestick.Candlestick.prototype.setLow = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional int64 timestamp = 6;
 * @return {number}
 */
proto.candlestick.Candlestick.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.candlestick.Candlestick} returns this
 */
proto.candlestick.Candlestick.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.candlestick.Candlesticks.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.candlestick.Candlesticks.prototype.toObject = function(opt_includeInstance) {
  return proto.candlestick.Candlesticks.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.candlestick.Candlesticks} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.candlestick.Candlesticks.toObject = function(includeInstance, msg) {
  var f, obj = {
    candlesticksList: jspb.Message.toObjectList(msg.getCandlesticksList(),
    proto.candlestick.Candlestick.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.candlestick.Candlesticks}
 */
proto.candlestick.Candlesticks.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.candlestick.Candlesticks;
  return proto.candlestick.Candlesticks.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.candlestick.Candlesticks} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.candlestick.Candlesticks}
 */
proto.candlestick.Candlesticks.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.candlestick.Candlestick;
      reader.readMessage(value,proto.candlestick.Candlestick.deserializeBinaryFromReader);
      msg.addCandlesticks(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.candlestick.Candlesticks.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.candlestick.Candlesticks.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.candlestick.Candlesticks} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.candlestick.Candlesticks.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCandlesticksList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.candlestick.Candlestick.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Candlestick candlesticks = 1;
 * @return {!Array<!proto.candlestick.Candlestick>}
 */
proto.candlestick.Candlesticks.prototype.getCandlesticksList = function() {
  return /** @type{!Array<!proto.candlestick.Candlestick>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.candlestick.Candlestick, 1));
};


/**
 * @param {!Array<!proto.candlestick.Candlestick>} value
 * @return {!proto.candlestick.Candlesticks} returns this
*/
proto.candlestick.Candlesticks.prototype.setCandlesticksList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.candlestick.Candlestick=} opt_value
 * @param {number=} opt_index
 * @return {!proto.candlestick.Candlestick}
 */
proto.candlestick.Candlesticks.prototype.addCandlesticks = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.candlestick.Candlestick, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.candlestick.Candlesticks} returns this
 */
proto.candlestick.Candlesticks.prototype.clearCandlesticksList = function() {
  return this.setCandlesticksList([]);
};


goog.object.extend(exports, proto.candlestick);
